ublox_version: 8
device: "/dev/nautonomous/gps"
frame_id: "gps_frame"
baudrate: 230400
all: true
rate: 20
nav_rate: 1
rtcm_ids: []
rtcm_rate: 1
dynamic_model: "portable"
fix_mode: "auto"
dr_limit: 30
enable_gps: true
enable_galileo: false
enable_beidou: false
enable_imes: false
enable_glonass: true
enable_qzss: false
enable_sbas: false
max_sbas: 0
sbas_usage: 0
enable_ppp: false