free_thresh: 0.196
image: /home/nvidia/ROS/WaternetNautonomous/src/nautonomous_configuration/config/map/amsterdam_cropped_.png
map_bottom: 5808353.0
map_left: -622507.0
map_right: -622407.0
map_top: 5808253.0
negate: 0
occupied_thresh: 0.65
origin: [-50.0, -50.0, 0.0]
resolution: 0.5
