free_thresh: 0.196
image: /home/waternet/waternet/nautonomous/workspaces/costmap_Test/src/WaternetNautonomous/src/nautonomous_configuration/config/map/amsterdam_test_cropped_amsterdam_test.png
map_bottom: 1060.0
map_left: 940.0
map_right: 1060.0
map_top: 940.0
negate: 0
occupied_thresh: 0.65
origin: [-60.0, -60.0, 0.0]
resolution: 1
