free_thresh: 0.196
image: /home/waternet/waternet/nautonomous/workspaces/default/src/WaternetNautonomous/src/nautonomous_configuration/config/navigation/map/amsterdam_test_cropped_amsterdam_test.png
map_bottom: 160.0
map_left: 40.0
map_right: 160.0
map_top: 40.0
negate: 0
occupied_thresh: 0.65
origin: [-60.0, -60.0, 0.0]
resolution: 0.25
