free_thresh: 0.196
image: /home/waternet/waternet/nautonomous/workspaces/default/src/WaternetNautonomous/src/nautonomous_configuration/config/map/amsterdam_cropped_handhaving.png
map_bottom: 5766.0
map_left: 5747.0
map_right: 6569.0
map_top: 2241.0
negate: 0
occupied_thresh: 0.65
origin: [628204.0, 5802537.0, 0.0]
resolution: 0.5
