free_thresh: 0.196
<<<<<<< HEAD:config/map/amsterdam_cropped_coenhaven.yaml
image: /home/waternet/waternet/nautonomous/workspaces/costmap_Test/src/WaternetNautonomous/src/nautonomous_configuration/config/map/amsterdam_cropped_coenhaven.png
=======
image: amsterdam_cropped_coenhaven.png
>>>>>>> master:config/navigation/map/amsterdam_cropped_coenhaven.yaml
map_bottom: 715.0
map_left: 4241.0
map_right: 4369.0
map_top: 587.0
negate: 0
occupied_thresh: 0.65
origin: [626698.0, 5807588.0, 0.0]
resolution: 0.5
