free_thresh: 0.196
image: /home/waternet/waternet/nautonomous/workspaces/default/src/WaternetNautonomous/src/nautonomous_configuration/config/navigation/map/amsterdam_cropped_coenhaven_dry_dock.png
map_bottom: 732.0
map_left: 4223.0
map_right: 4335.0
map_top: 621.0
negate: 1
occupied_thresh: 0.65
origin: [626680.0, 5807571.0, 0.0]
resolution: 0.5
