local_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  transform_tolerance: 0.5
  update_frequency: 2.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.5
  escape_vel: -3.0
  sim_time: 5.0
  max_vel_x: 10.0
  min_vel_x: 0.05
  controller_frequency: 10.0
