TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  dwa: false                          #I prefer trajectory rollout as I can see it in rviz

  xy_goal_tolerance: 5                #default is 10cm but I think AMCL makes it too giggly for this to be safe (* resolution (=0.5 now))
  yaw_goal_tolerance: 6.2             #default is 0.05 rad (~3 degrees), I changed it to 5

  controller_frequency: 10.0
  sim_granularity: 0.5
  sim_time: 5.0
