obstacle_range: 30.0
raytrace_range: 30.0
footprint: [[1.3,1.0], [1.3,-1.0], [-1.3,-1.0], [-1.3, 1.0]]
#robot_radius: ir_of_robot
inflation_radius: 1.0

observation_sources: base_scan

#base_scan: {data_type: LaserScan, expected_update_rate: 0.4, topic: /base_scan, inf_is_valid: true,  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 2.0, min_obstacle_height: 0.0001}

publish_voxel_map: true

sim_granularity: 0.5
sim_time: 5.0

transform_tolerance: 0.5
