obstacle_range: 25.0
raytrace_range: 30.0
footprint: [[0.01,0.01], [0.01,-0.01], [-0.01,-0.01], [-0.01, 0.01]]
robot_radius: 0.1
inflation_radius: 0.1

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: scan_link, data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: scan_link, data_type: PointCloud2, topic: /sensor/scan/point_cloud, marking: true, clearing: true}
