global_frame: /odom_combined
robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 2.0
max_vel_x: 10.0
min_vel_x: 0.05

#set if you want the voxel map published
publish_voxel_map: true

#set to true if you want to initialize the costmap from a static map
static_map: true

#begin - COMMENT these lines if you set static_map to true
rolling_window: true
width: 150.0
height: 150.0
resolution: 0.5
#end - COMMENT these lines if you set static_map to true

#START VOXEL STUFF
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 10
mark_threshold: 0
#END VOXEL STUFF

transform_tolerance: 1.0
obstacle_range: 150.0
max_obstacle_height: 10.0
raytrace_range: 150.0
footprint: [[0.01,0.01], [0.01,-0.01], [-0.01,-0.01], [-0.01, 0.01]]
#robot_radius: 0.46
footprint_padding: 0.25
controller_frequency: 10.0
inflation_radius: 0.5
cost_scaling_factor: 10.0
lethal_cost_threshold: 100

