global_frame: /odom_combined
robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 2.0
max_vel_x: 10.0
min_vel_x: 0.05

#set if you want the voxel map published
publish_voxel_map: true

#set to true if you want to initialize the costmap from a static map
static_map: true

#begin - COMMENT these lines if you set static_map to true
rolling_window: true
width: 10.0
height: 10.0
resolution: 1.0
#end - COMMENT these lines if you set static_map to true

#START VOXEL STUFF
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 10
mark_threshold: 0
#END VOXEL STUFF

transform_tolerance: 1.0
obstacle_range: 10.0
max_obstacle_height: 10.0
raytrace_range: 10.0
footprint: [[1.3,1.0], [1.3,-1.0], [-1.3,-1.0], [-1.3, 1.0]]
#robot_radius: 0.46
footprint_padding: 0.25
controller_frequency: 10.0
inflation_radius: 1.0
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
observation_sources: base_scan
#base_scan: {data_type: LaserScan, expected_update_rate: 0.4, topic: /base_scan, inf_is_valid: true,  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 2.0, min_obstacle_height: 0.0001}


